import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MenuBar } from "./components/menu-bar";
import Layout from "./components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en light">
      <body>
        <Layout>
          {children}

          <div className="w-full relative flex flex-col items-center">
            <MenuBar />
          </div>
        </Layout>
      </body>
    </html>
  );
}
